### ISSUE TITLE
Fairytale 부분에 질문이 있습니다.

### ISSUE THREAD

**Issue by Ho-Joon-Kim** [aiwebnovel/writinggel-front#11]
src/Components/app/page/Fairytale,js 수정중에 어떻게 체크해야 할지 모르겠는게 있어 질문드립니다.
9번 줄에서 onChange로 받아오는 객체에는 내용만 있어서 어떤 카테고리의 input인지 체크가 안되는데 어떻게 처리해야 하나요?

![code](https://user-images.githubusercontent.com/45334530/141168309-6431eaeb-534c-4f55-888c-be27b2418c4d.png)
.

**Comment by alissa1228** [comment]
`<Accordion className='AcoStyle' onActive={(e)=>console.log('item',e[0])}>
                  {AccodianData.map((item) => (
                    <AccordionPanel
                      key={item.id}
                      label={item.title}
                      className='AcoPanelStyle'
                    >
                      <div className='AcoInput'>
                        <input type='text' name={item.title} onChange={(e)=> {
                          console.log('e',e);
                          console.log('category', e.target.name);
                        }}/>
                        <button>추가</button>
                      </div>
                    </AccordionPanel>
                  ))}
                  <div className="writeBtn"><button >write</button></div>
                </Accordion>`


-  Accodion 컴포넌트에 있는 onActive 사용해서 저렇게 콘솔을 찍어보면 현재 액티브 되어 있는 패널의 인덱스를 얻을 수 있습니다. 지금 대략적으로 봤을 때는 저걸 사용하거나 input name 쪽에 item.title이나 item.id를 넣어서 웹노블 때처럼 state에 각각 넣어봐야 할 거 같네요

**Comment by alissa1228** [comment]
```javascript

  const [category, Setcategory] = useState({
    story:'',
    mainCharacter:'',
    period:'',
    location:'',
    theme:'',
  });

  const { story, mainCharacter, period, location, theme} = category

  const HandleInput = (e) => {
    console.log('e',e);
    console.log('category', e.target.name);
    console.log('input', e.target.value)

    if(e.target.name === '주요 인물') {
      Setcategory({
      ...category,
      mainCharacter : e.target.value
      })
    }
    if(e.target.name === '장소') {
      Setcategory({
      ...category,
      location : e.target.value
      })
    }
    if(e.target.name === '시간') {
      Setcategory({
      ...category,
      period : e.target.value
      })
    }
    if(e.target.name === '주요 사건') {
      Setcategory({
      ...category,
      story : e.target.value
      })
    }
    if(e.target.name === '소재') {
      Setcategory({
      ...category,
      theme : e.target.value
      })
    }
    console.log('result', story, mainCharacter, period, location, theme);

  }
```

```javascript
  <Accordion className='AcoStyle' multiple >
    {AccodianData.map((item) => (
      <AccordionPanel
        key={item.id}
        label={item.title}
        className='AcoPanelStyle'
      >
        <div className='AcoInput'>
          <input type='text' name={item.title} onChange={(e) => HandleInput(e)}/>
          <button>추가</button>
        </div>
      </AccordionPanel>
    ))}
    <div className="writeBtn"><button >write</button></div>
  </Accordion>
```

- 일단 이렇게 수정해봤습니다. 한 번 해보시고 안되면 다시 이야기 해봐요!

**Comment by Ho-Joon-Kim** [comment]
넵 체크해 보겠습니다!
