### ISSUE TITLE
비지니스 아이템 500번 오류

### ISSUE THREAD

**Issue by alissa1228** [aiwebnovel/writinggel-front#14]
- 다른 건 잘 되는데 비지니스 아이템 쪽에서 500번 오류 나네요..!

`xhr.js:210 POST https://veryshort.best:5051/api/v1/writinggel/businessitem 500 (Internal Server Error)`

![스크린샷 2021-11-11 오전 10 48 54](https://user-images.githubusercontent.com/68986081/141224800-e9ac3f7b-c15f-4c80-a9e8-8c9e266da27f.png)
![스크린샷 2021-11-11 오전 10 49 05](https://user-images.githubusercontent.com/68986081/141224807-8924582e-dd2c-43b0-a4c9-f46e3f9fc4c4.png)

**Comment by Ho-Joon-Kim** [comment]
수정 되었습니다!
